#! /bin/bash 

caen-two-01 --dataset-name $1  --run-number $2 --max-triggers $3 --run --sample-rate 2.5 --num-samples 1024 --trigger-edge rising --trigger-delay 0 --digitize-trigger

#Command line parameters:
#  --status                        Display the status of the digitizer board.
#  --run                           Configure the board to acquire data and read out
#                                  data once it is acquired.
#  --test-mode                     Replace ADC samples with a sawtooth generated by
#                                  the FPGA.
#  --digitize-trigger              Digitize the TR0 and TR1 signals and include
#                                  them in the output data.
#  --sample-rate                   Set the sample rate.  Can be 5, 2.5 or 1.
#  --num-samples                   Set the number of samples to take per trigger.
#                                  Can be 1024, 520, 256 or 136.
#  --software-trigger              Trigger an acquistion with the software
#                                  trigger.
#  --max-triggers                  Maximum number of triggers to take before exiting.
#  --split-data [file]             Read in the raw data from the digitizer and
#                                  split it into individual files for each channel.
#                                  The metadata is removed and each file only contains
#                                  the samples for that channel.
#  --dataset-name                  Specificy the name of the dataset which will be used
#                                  to construct output file names.  This is required.
#  --run-number [run]              Specify the run number.  This will be used to
#                                  construct output file names and will override the
#                                  --runNumberFileName parameter.
#  --trigger-edge [rising|falling] Configure whether readout is triggered on the risiing
#                                  or falling edge.
#  --trigger-delay [delay]         The amount of time to wait after the trigger before the
#                                  the start of digitization.  Specified in steps on 8.5ns.
#  --buffer-limit                  Prevent all the board's buffer from being used.  If data
#                                  readout falls behind acquisition turn off acquisition.
#  --sift-data                     Attempt to sift through the data read out of the board
#                                  throwing out bad triggers and grouping data based on the
#                                  group time tag.
